fundacion apoyo/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('network.urls', namespace='network')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fundacion apoyo/network/urls.py
from django.urls import path
from . import views


app_name = 'network'

urlpatterns = [
    path('', views.home, name='home'),
    path('agregarAporte', views.agregarAporte, name='agregarAporte'),
    path('agregarAnotacion', views.agregarAnotacion, name='agregarAnotacion'),
    path('anotaciones', views.anotaciones, name='anotaciones'),
    path('aportes', views.aportes, name='aportes'),
    path('controlResidentes', views.controlResidentes, name='controlResidentes'),
    path('fichapaciente', views.fichapaciente, name='fichapaciente'),
    path('informacion', views.informacion, name='informacion'),
    path('ingresos', views.ingresos, name='ingresos'),
    path('insumos', views.insumos, name='insumos'),
    path('residentesAfuera', views.residentesAfuera, name='residentesAfuera'),
]

fundacion apoyo/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

fundacion apoyo/network/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
import uuid

class Post(models.Model):
    identifier = models.UUIDField(primary_key=True, default=uuid.uuid4)
    slug = models.SlugField(max_length=250)
    description = models.TextField()
    image = models.ImageField(
        upload_to='images/',
        default='images/default.png'
    )
    published = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='network_post'
    )

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.description

fundacion apoyo/users/models.py
import random
import string

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from network.models import Post


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class CustomAccountManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,
                          last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **other_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    profile_pic = models.ImageField(
        upload_to='users/', default='users/default.png')
    bio = models.TextField(_(
        'Bio'), max_length=500, blank=True)
    followers = models.ManyToManyField(
        "self",
        related_name='following',
        symmetrical=False,
        blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    register_date = models.DateTimeField(default=timezone.now)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.slug])

    def count_following(self):
        users_following = UserProfile.objects.filter(followers=self)
        print(users_following)
        return users_following.count()

    def count_posts(self):
        return Post.objects.filter(author=self).count()

    def is_follower(self, other_user):
        if UserProfile.objects.filter(followers=other_user):
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + self.email)
        super(UserProfile, self).save(*args, **kwargs)

fundacion apoyo/users/forms.py
from django import forms


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'loginEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'loginPassword',
            'type': 'password',
            'class': 'form-control',
        })
    )


class UserSignUpForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'signupEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    first_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))

    last_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'signupPassword',
                'type': 'password',
                'class': 'form-control'
            }
        ))

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control'
            }
        ))

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las Contraseñas no coinciden')
        return cd['password2']

fundacion apoyo/network/views.py
from django.shortcuts import render
from .models import Post


def home(request):
    data = Post.objects.all()
    return render(request, 'network/home.html', {'posts': data})


def agregarAporte(request):
    return render(request, 'network/agregar_aporte.html')

def agregarAnotacion(request):
    return render(request, 'network/agregaranotacion.html')

def anotaciones(request):
    return render(request, 'network/anotaciones.html')

def aportes(request):
    return render(request, 'network/aportes.html')

def controlResidentes(request):
    return render(request, 'network/Control_de_residentes.html')

def fichapaciente(request):
    return render(request, 'network/ficha_paciente.html')

def informacion(request):
    return render(request, 'network/informacion.html')

def ingresos(request):
    return render(request, 'network/ingresos.html')

def insumos(request):
    return render(request, 'network/insumos.html')

def residentesAfuera(request):
    return render(request, 'network/residentes_fuera.html')

fundacion apoyo/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import UserLoginForm, UserSignUpForm


def login_view(request):
    login_form = UserLoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Has iniciado sesion correctamente')
            return redirect('network:home')
        else:
            messages.warning(
                request, 'Correo Electronico o Contrasena invalida')
            return redirect('network:home')

    messages.error(request, 'Formulario Invalido')
    return redirect('network:home')


def signup_view(request):
    signup_form = UserSignUpForm(request.POST or None)
    if signup_form.is_valid():
        email = signup_form.cleaned_data.get('email')
        first_name = signup_form.cleaned_data.get('first_name')
        last_name = signup_form.cleaned_data.get('last_name')
        password = signup_form.cleaned_data.get('password')
        try:
            user = get_user_model().objects.create(
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=make_password(password),
                is_active=True
            )
            login(request, user)
            return redirect('users:profile')

        except Exception as e:
            print(e)
            return JsonResponse({'detail': f'{e}'})


def logout_view(request):
    logout(request)
    return redirect('network:home')


@login_required(login_url='network:home')
def profile_view(request):
    return render(request, 'network/user/profile.html')


def user_detail(request, slug):
    user = get_object_or_404(get_user_model(), slug=slug)
    is_follower = False
    try:
        if user.is_follower(request.user):
            is_follower = True
    except:
        messages.warning(
            request, 'Debes Iniciar sesion para mas funcionalidades')

    return render(request, 'network/user/user_detail.html', {'user_detail': user, "is_follower": is_follower})


@login_required(login_url='network:home')
def follow(request, slug):
    to_follow = get_object_or_404(get_user_model(), slug=slug)
    if to_follow.is_follower(request.user):
        to_follow.followers.remove(request.user)
    else:
        to_follow.followers.add(request.user)
    to_follow.save
    return redirect(to_follow)

fundacion apoyo/network/templates/network/user/login.html
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <ul class="nav nav-pills nav-justified mb-3">
          <li class="nav-item">
            <a class="nav-link active show" data-mdb-toggle="pill" href="#navbarLogin-login" role="tab">
              Iniciar Sesion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-mdb-toggle="pill" href="#navbarLogin-signup" role="tab">Registrarse</a>
          </li>
        </ul>

        <div class="tab-content" id="tab-content">
          <div class="tab-pane fade show active" id="navbarLogin-login" role="tabpanel">
            <form id="login" class="text-center" action="{% url 'users:login' %}" method="post">
              {% csrf_token %}

              <div class="form-outline form-auth-md mb-4">
                {{ loginForm.email }}
                <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
              </div>

              <div class="form-outline form-auth-md mb-4">
                {{ loginForm.password }}
                <label class="form-label" style="margin-left: 0px;">Contraseña</label>
              </div>



              <button type="submit" class="btn btn-primary btn-block mb-4">Iniciar</button>
            </form>
          </div>


          <div class="tab-pane fade" id="navbarLogin-signup" role="tabpanel">
            <form id="register" class="text-center" action="{% url 'users:signup'%}" method="post">
              {% csrf_token %}
              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.email}}
                <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.first_name }}
                <label class="form-label" style="margin-left: 0px;">Nombre</label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.last_name }}
                <label class="form-label" style="margin-left: 0px;">Apellido</label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.password }}
                <label class="form-label" style="margin-left: 0px;">Your password
                </label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.password2 }}
                <label class="form-label" style="margin-left: 0px;">Repeat password
                </label>

              </div>

              <button class="btn btn-primary btn-block mb-3" type="submit">Registrar</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

fundacion apoyo/network/templates/network/user/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="network/estilos.css">

  <title>Ayuda a los ancianos</title>
</head>

<body class="body1">

  <!--=========================================-->
  <!--ENCABEZADO-->
  <!--=========================================-->

  <header>



    <nav class="navbar navbar-expand-sm   fixed-top " style="background-color: rgb(135, 206, 235);">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="https://cdn.iconscout.com/icon/free/png-256/network-nodes-connection-sharing-social-media-1-9592.png"
            class="me-2" height="40" alt="" loading="lazy" />
          <small>My Network</small>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto centrado">
            <li class="nav-item">
              <a class="nav-link" href="/">INICIO</a>
            </li>
          
          </ul>

          <div class="d-flex align-items-center me-3">
            {% if user.is_authenticated %}
            <a href={% url 'users:profile' %}>
              <img src={{ user.profile_pic.url }} class="rounded-circle" height="30" width='30' alt="" loading="lazy" />
            </a>
            {% else %}
            <button type="button" class="btn btn-primary" data-mdb-toggle='modal' data-mdb-target='#loginModal'>
              Iniciar Sesión
            </button>
            {% endif %}
          </div>

        </div>
      </div>
    </nav>



  </header>

  <div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
    <div class="card shadow-4-strong mb-3" style="margin-top: 13%;">
      <div class="row g-0">
        <div class="col-md-5">
          <img src={{ user.profile_pic.url }} alt="..." class="img-fluid rounded" />
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <div class='row justify-content-center'>
              <h4 class="col-12 card-title text-center mb-4">{{ user.first_name}} {{ user.last_name}}</h4>

              <p class="card-text text-center mb-5">{{ user.bio }}</p>

              <a class='btn btn-danger btn-rounded col-5' href={% url 'users:logout' %}>
                Cerrar Sesion
              </a>

            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

 

</body>

</html>

fundacion apoyo/network/templates/network/user/user_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="css_ficha_paciente/estilos.css">

  <title>Ayuda a los ancianos</title>
</head>

<body class="body1">

  <!--=========================================-->
  <!--ENCABEZADO-->
  <!--=========================================-->

  <header>



    <nav class="navbar navbar-expand-sm   fixed-top " style="background-color: rgb(135, 206, 235);">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="https://cdn.iconscout.com/icon/free/png-256/network-nodes-connection-sharing-social-media-1-9592.png"
            class="me-2" height="40" alt="" loading="lazy" />
          <small>My Network</small>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto centrado">
            <li class="nav-item">
              <a class="nav-link" href="/">INICIO</a>
            </li>
          
          </ul>

          <div class="d-flex align-items-center me-3">
            {% if user.is_authenticated %}
            <a href={% url 'users:profile' %}>
              <img src={{ user.profile_pic.url }} class="rounded-circle" height="30" width='30' alt="" loading="lazy" />
            </a>
            {% else %}
            <button type="button" class="btn btn-primary" data-mdb-toggle='modal' data-mdb-target='#loginModal'>
              Iniciar Sesión
            </button>
            {% endif %}
          </div>

        </div>
      </div>
    </nav>



  </header>
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3" style="margin-top: 13%;">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user_detail.profile_pic.url }} alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class='row justify-content-center'>
            <h4 class="col-12 card-title text-center mb-4">{{ user_detail.first_name}} {{ user_detail.last_name}}</h4>


            <p class="card-text text-center mb-5">{{ user_detail.bio }}</p>
            {% if is_follower %}
            <a type="button" class="btn btn-secondary btn-rounded col-5"
              href={% url 'users:follow' slug=user_detail.slug %}>Dejar de Seguir</a>
            {% elif user_detail != user and user.email %}
            <a type="button" id='follow' class="btn btn-primary btn-rounded col-5"
              href={% url 'users:follow' slug=user_detail.slug %}>Seguir</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>