fundacion apoyo/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('network.urls', namespace='network')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fundacion apoyo/network/urls.py
from django.urls import path
from . import views


app_name = 'network'

urlpatterns = [
    path('', views.home, name='home'),
    path('agregarAporte', views.agregarAporte, name='agregarAporte'),
    path('agregarAnotacion', views.agregarAnotacion, name='agregarAnotacion'),
    path('anotaciones', views.anotaciones, name='anotaciones'),
    path('aportes', views.aportes, name='aportes'),
    path('controlResidentes', views.controlResidentes, name='controlResidentes'),
    path('fichapaciente', views.fichapaciente, name='fichapaciente'),
    path('informacion', views.informacion, name='informacion'),
    path('ingresos', views.ingresos, name='ingresos'),
    path('insumos', views.insumos, name='insumos'),
    path('residentesAfuera', views.residentesAfuera, name='residentesAfuera'),
]

fundacion apoyo/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

fundacion apoyo/network/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
import uuid

class Post(models.Model):
    identifier = models.UUIDField(primary_key=True, default=uuid.uuid4)
    slug = models.SlugField(max_length=250)
    description = models.TextField()
    image = models.ImageField(
        upload_to='images/',
        default='images/default.png'
    )
    published = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='network_post'
    )

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.description

fundacion apoyo/network/views.py
from django.shortcuts import render
from .models import Post


def home(request):
    data = Post.objects.all()
    return render(request, 'network/home.html', {'posts': data})


def agregarAporte(request):
    return render(request, 'network/agregar_aporte.html')

def agregarAnotacion(request):
    return render(request, 'network/agregaranotacion.html')

def anotaciones(request):
    return render(request, 'network/anotaciones.html')

def aportes(request):
    return render(request, 'network/aportes.html')

def controlResidentes(request):
    return render(request, 'network/Control_de_residentes.html')

def fichapaciente(request):
    return render(request, 'network/ficha_paciente.html')

def informacion(request):
    return render(request, 'network/informacion.html')

def ingresos(request):
    return render(request, 'network/ingresos.html')

def insumos(request):
    return render(request, 'network/insumos.html')

def residentesAfuera(request):
    return render(request, 'network/residentes_fuera.html')

fundacion apoyo/network/templates/network/Control_de_residentes.html
{% extends "./base.html" %}

{% block content %}
{% load static %}
<!--=========================================-->
<!--ENCABEZADO-->
<!--=========================================-->



<!--=========================================-->
<!--INTRO-->
<!--=========================================-->
<section class="container-fluid " style="margin-top: 14%;">

    <div class=" row">
        <div class="col-md-2 hidden-sm"></div>
        <div class=" row col-md-8 col-sm-8 ">
            <nav class="navbar navbar-expand-sm navbar-dark espaciado borde2 centrado">
                <div class="container-fluid letrasinicio">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbarr">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="mynavbarr">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link text-write" href="controlResidentes">VER TOTAL DE RESIDENTES</a>
                            </li>
                        </ul>

                        <ul class="nav justify-content-end navbar-nav centrado">
                            <li class="nav-item">
                                <a class="nav-link text-write" href="residentesAfuera">VER RESIDENTES FUERA </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="col-md-2 hidden-sm"></div>

    </div>

    <div class=" row espaciado centrado">
        <div class="col-md-3 hidden-sm"></div>
        <div class="borde2 centrado col-md-6 col-ms-6 ">
            <h5> TOTAL DE RESIDENTES</h5>
        </div>
        <div class="col-md-3 hidden-sm"></div>
    </div>



    <div class="row w-100 mx-auto ">


        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <p class="card-text text-righf">
                        <a class="btn btn-dark" href="#" role="button">MOVER A RESIDENTES FUERA</a>
                    </p>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">
            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <p class="card-text text-righf">
                        <a class="btn btn-dark" href="#" role="button">MOVER A RESIDENTES FUERA</a>
                    </p>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">
            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <p class="card-text text-righf">
                        <a class="btn btn-dark" href="#" role="button">MOVER A RESIDENTES FUERA</a>
                    </p>
                </div>
            </div>

        </div>
    </div>


    <div class="row w-100 mx-auto catalogos-autos">

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">
            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <p class="card-text text-righf">
                        <a class="btn btn-dark" href="#" role="button">MOVER A RESIDENTES FUERA</a>
                    </p>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">
            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <p class="card-text text-righf">
                        <a class="btn btn-dark" href="#" role="button">MOVER A RESIDENTES FUERA</a>
                    </p>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">
            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <p class="card-text text-righf">
                        <a class="btn btn-dark" href="#" role="button">MOVER A RESIDENTES FUERA</a>
                    </p>
                </div>
            </div>

        </div>

    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                        <a class="page-link" href="#">Anterior</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>

                    <li class="page-item">
                        <a class="page-link" href="#">Siguiente</a>
                    </li>
                </ul>
            </nav>

        </div>



    </div>






</section>

<!--=========================================-->
<!--PIE DE PAGINA-->
<!--=========================================-->

<footer class="w-100  d-flex aling-items justify-content-center" style="background-color:  rgb(135, 206, 235);">
    <p class="fs-7 px-3 pt-3" style="font-weight: bold;">GODES &copy; Derechos Reservados 2022</p>

</footer>






<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>



{% endblock %}

fundacion apoyo/network/templates/network/agregar_aporte.html
{% extends "./base.html" %}

{% block content %}
{% load static %}

<div class=" container centrado">

  <div class="row" style="margin-top: 12%; margin-bottom: 4%;">
    <div class="col-md-2 hidden-sm"></div>

    <div class="col-md-8 col-sm-12  borde2">
      <form action="aportes" id="enviarmensajeadmi" enctype="multipart/form-data" name="mensajealadmi">
        <h2 class="centrado letrasregistroylogin">AQUI PODRA AGREGAR UN APORTE AL ASILO</h2>
        <div class="row letrasregistroylogin">


          <div class="form-group col-md-12 col-sm-12">
            <label>
              <h4>Ingrese su primer nombre</h4>
            </label>
            <input type="text" name="nombreaportador" class="form-control" required>
          </div>

          <div class="form-group col-md-12 col-sm-12">
            <label>
              <h4>Ingrese su primer apellido</h4>
            </label>
            <input type="text" name="apellidoaportador" class="form-control" required>
          </div>

          <div class="form-group col-md-12 col-sm-12">
            <label>
              <h4>Ingrese su Edad</h4>
            </label>
            <input type="text" name="edadaportador" class="form-control" required>
          </div>

          <div class="form-group col-md-12 col-sm-12">
            <label>
              <h4>Ingrese su correo Electronico para enviarle un comprobante </h4>
            </label>
            <input type="email" name="correoaportador" class="form-control" required>
          </div>


          <div class="form-group col-md-12 col-sm-12">
            <label>
              <h4>Ingrese un pequeño mensaje que quiera darnos</h4>
            </label>
            <input type="text" name="mensajeaportador" class="form-control" required>
          </div>




          <div class="col-md-3  col-sm-3"></div>
          <div class="row espaciado col-md-6 col-sm-6 ">
            <button style="border-radius:10px; background-color: rgb(135, 206, 235);" type="submit ">
              <h5>Enviar aporte</h5>
            </button>
          </div>
          <div class="col-md-3 col-sm-3 "></div>

          <div class="col-md-3 col-sm-5 "></div>
          <div class="col-md-3 col-sm-5 espaciado"></div>


        </div>
      </form>
    </div>
    <div class="col-md-2 hidden-sm"></div>
  </div>

</div>




{% endblock %}

fundacion apoyo/network/templates/network/agregaranotacion.html
{% extends "./base.html" %}

{% block content %}
{% load static %}



    <div class=" container centrado">

        <div class="row" style="margin-top: 12%; margin-bottom: 4%;">
            <div class="col-md-2 hidden-sm"></div>

            <div class="col-md-8 col-sm-12  borde2">
                <form action="informacion"  enctype="multipart/form-data" name="agregaranotaciones">
                    <h2 class="centrado letrasregistroylogin">AQUI PODRA AGREGAR LAS ANOTACIONES</h2>
                    <div class="row letrasregistroylogin">



                        <div class="form-group col-md-12 col-sm-12">
                            <label>
                                <h4>Ingrese la anotacion que le quiera realizar al residente</h4>
                            </label>
                            <textarea type="text" class="form-control" rows="5"  name="text"
                                required></textarea>
                        </div>
                        
                        

                        <div class="col-md-3  col-sm-3"></div>
                        <div class="row espaciado col-md-6 col-sm-6 ">
                            <button type="submit" style="background-color: rgb(135, 206, 235);">
                                <h5>Enviar mensaje</h5>
                            </button>
                        </div>
                        <div class="col-md-3 col-sm-3 "></div>

                        <div class="col-md-3 col-sm-5 "></div>
                        <div class="col-md-3 col-sm-5 espaciado"></div>


                    </div>
                </form>
            </div>
            <div class="col-md-2 hidden-sm"></div>
        </div>

    </div>





  


{% endblock %}

fundacion apoyo/network/templates/network/anotaciones.html
{% extends "./base.html" %}

{% block content %}
{% load static %}





  <div class="row espaciado  letrasinicio " style="margin-top: 5%; margin-bottom: 5%;">
    <div class="col-md-1 hidden-sm"></div>


    <div class="col-sm-10 col-md-10  espaciado">
      <div class="card  borde1 letrasinicio">
        <div class="card-body centrado">
            <p class="card-text text-righf">
                <a class="btn btn-dark" href="informacion" role="button">VOlVER A FICHA DEL RESIDENTE</a>
              </p>
            <h3>ANOTACIONES DEL RESIDENTE </h3>
          

            <div class="row espaciado centrado borde2">
              
    
    
                <div class="col-sm-12 col-md-12 centrado espaciado">
                  <h3 class="espaciado">1) ESTE RESIDENTE ES MUY ADICTO A LOL JUGANDOLO 12 HORAS AL DIA PARA LA EDAD QUE TIENE , AL MENOS LE SIRVE <PARAm>
                    CALMAR LA SOLEDAD QUE TIENE</h3>
                </div>

                <div class="col-sm-12 col-md-12 centrado espaciado">
                    <h3 class="espaciado">2) ESTE RESIDENTE ES MUY ADICTO A LOL JUGANDOLO 12 HORAS AL DIA PARA LA EDAD QUE TIENE , AL MENOS LE SIRVE <PARAm>
                      CALMAR LA SOLEDAD QUE TIENE</h3>
                  </div>

                  <div class="col-sm-12 col-md-12 centrado espaciado">
                    <h3 class="espaciado">3) ESTE RESIDENTE ES MUY ADICTO A LOL JUGANDOLO 12 HORAS AL DIA PARA LA EDAD QUE TIENE , AL MENOS LE SIRVE <PARAm>
                      CALMAR LA SOLEDAD QUE TIENE</h3>
                  </div>

                  <div class="col-sm-12 col-md-12 centrado espaciado">
                    <h3 class="espaciado">4) ESTE RESIDENTE ES MUY ADICTO A LOL JUGANDOLO 12 HORAS AL DIA PARA LA EDAD QUE TIENE , AL MENOS LE SIRVE <PARAm>
                      CALMAR LA SOLEDAD QUE TIENE</h3>
                  </div>

                  <div class="col-sm-12 col-md-12 centrado espaciado">
                    <h3 class="espaciado">5) ESTE RESIDENTE ES MUY ADICTO A LOL JUGANDOLO 12 HORAS AL DIA PARA LA EDAD QUE TIENE , AL MENOS LE SIRVE <PARAm>
                      CALMAR LA SOLEDAD QUE TIENE</h3>
                  </div>
    
              </div>











        </div>
      </div>
    </div>
    <div class="col-md1 hidden-sm"></div>
  </div>





  {% endblock %}

fundacion apoyo/network/templates/network/aportes.html
{% extends "./base.html" %}

{% block content %}
{% load static %}

<!--=========================================-->
<!--INTRO-->
<!--=========================================-->
<section class="container-fluid " style="margin-top: 12%;">



    <div class=" row espaciado centrado">
        <div class="col-md-3 hidden-sm"></div>
        <div class="borde2 centrado col-md-6 col-ms-6 ">
            <p class="card-text text-righf">
                <a class="btn btn-dark" href="agregarAporte" role="button">AGRREGAR APORTE</a>
            </p>
            <p class="card-text text-righf">
                <a class="btn btn-dark" href="ingresos" role="button">VER INGRESOS DEL ASILO</a>
            </p>
            <h5> LISTA DE APORTADORES</h5>
        </div>
        <div class="col-md-3 hidden-sm"></div>
    </div>



    <div class="row w-100 mx-auto ">


        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <h5 class="card-title">aportado: 200 MIL PESOS</h5>
                    <h5 class="card-title">Pequeño mensaje: <br> aporto esto por que quiero que los ancianos tenga un
                        buen cuidado</h5>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <h5 class="card-title">aportado: 200 MIL PESOS</h5>
                    <h5 class="card-title">Pequeño mensaje: <br> aporto esto por que quiero que los ancianos tenga un
                        buen cuidado</h5>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <h5 class="card-title">aportado: 200 MIL PESOS</h5>
                    <h5 class="card-title">Pequeño mensaje: <br> aporto esto por que quiero que los ancianos tenga un
                        buen cuidado</h5>
                </div>
            </div>

        </div>
    </div>


    <div class="row w-100 mx-auto catalogos-autos">

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <h5 class="card-title">aportado: 200 MIL PESOS</h5>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <h5 class="card-title">aportado: 200 MIL PESOS</h5>
                    <h5 class="card-title">Pequeño mensaje: <br> aporto esto por que quiero que los ancianos tenga un
                        buen cuidado</h5>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-12 col-sm-12  my-5 d-flex centrado justify-content-center  ">

            <div class="card borde2" style="width: 20rem;">
                <img src="{% static 'network/img/padre.png' %}" class="card-img-top" alt="test">
                <div class="card-body">
                    <h5 class="card-title">nombre: Axel Cisternas</h5>
                    <h5 class="card-title">Edad: 72 años</h5>
                    <h5 class="card-title">aportado: 200 MIL PESOS</h5>
                    <h5 class="card-title">Pequeño mensaje: <br> XXX</h5>
                </div>
            </div>

        </div>

    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                        <a class="page-link" href="#">Anterior</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>

                    <li class="page-item">
                        <a class="page-link" href="#">Siguiente</a>
                    </li>
                </ul>
            </nav>

        </div>



    </div>






</section>

<!--=========================================-->
<!--PIE DE PAGINA-->
<!--=========================================-->

<footer class="w-100  d-flex aling-items justify-content-center" style="background-color:rgb(135, 206, 235);">
    <p class="fs-7 px-3 pt-3" style="font-weight: bold;">GODES &copy; Derechos Reservados 2022</p>

</footer>






<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>



{% endblock %}

fundacion apoyo/network/templates/network/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{%static 'network/css/estilos.css'%}" />
</head>

<body class="body1">
  {% include "network/user/login.html" %}
  <header>



    <nav class="navbar navbar-expand-sm   fixed-top " style="background-color: rgb(135, 206, 235);">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="https://cdn.iconscout.com/icon/free/png-256/network-nodes-connection-sharing-social-media-1-9592.png"
            class="me-2" height="40" alt="" loading="lazy" />
          <small>My Network</small>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto centrado">
            <li class="nav-item">
              <a class="nav-link" href="/">INICIO</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="fichapaciente">FICHA PACIENTE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="controlResidentes">GESTION DE RESIDENTES</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="aportes">APORTES</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="insumos">INSUMOS</a>
            </li>
          </ul>

          <div class="d-flex align-items-center me-3">
            {% if user.is_authenticated %}
            <a href={% url 'users:profile' %}>
              <img src={{ user.profile_pic.url }} class="rounded-circle" height="30" width='30' alt="" loading="lazy" />
            </a>
            {% else %}
            <button type="button" class="btn btn-primary" data-mdb-toggle='modal' data-mdb-target='#loginModal'>
              Iniciar Sesión
            </button>
            {% endif %}
          </div>

        </div>
      </div>
    </nav>



  </header>

  {% for message in messages %}
  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
    {{ message }}
  </div>
  {% endfor %}

  <div id="content">{% block content %} {% endblock %}</div>

</body>

<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

</html>

fundacion apoyo/network/templates/network/home.html
{% extends "./base.html" %}

{% block content %}
{% load static %}
<div class='container col-md-8 col-xl-6'>
  <h1 class='text-center my-4'>Últimos Posts</h1>


  <div id="carouselExampleControls" class="carousel slide" style="margin-top: 4%;" data-bs-ride="carousel">
    <div class="carousel-inner">

      <div class="carousel-item active" data-bs-slide="3000">
        <img src="{% static 'network/img/Slider1.jpg' %}"  class="d-block w-100" alt="slider1">
      </div>

      <div class="carousel-item" data-bs-slide="3000">
        <img src="{% static 'network/img/ancianos.jpg' %}"  class="d-block w-100" alt="slider2">
      </div>

      <div class="carousel-item" data-bs-slide="3000">
        
        <img src="{% static 'network/img/Slider3.png' %}" class="d-block w-100" alt="slider3">
      </div>

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!--=========================================-->
  <!--INTRO-->
  <!--=========================================-->

  <section class="w-50 mx-auto text-center pt-5" id="intro">
    <h1 class="p-3 fs-2 border-top border-3 pt-5">Bienvenido a "Ayuda a los <span
        style="color: rgb(135, 206, 235);;">Ancianos</span>" </h1>
    <p class="p-3 fs-4">Aqui podras realizar aportes para nuestra fundación, registrar tus abuelos y mucho más</p>

  </section>


  <!--=========================================-->
  <!--PIE DE PAGINA-->
  <!--=========================================-->

  <footer class="w-100 d-flex aling-items justify-content-center" style="background-color: rgb(135, 206, 235); margin-top: 370px;">
    <center>
      <p class="fs-5 px-3 pt-3" style="font-weight: bold;">Ayuda a un anciano &copy; Derechos Reservados 2022</p>
    </center>

  </footer>




  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>






</div>

{% endblock %}